openapi: 3.0.0
info:
  title: Kubernetes Log Viewer API
  version: 0.0.1
paths:
  /logs:
    get:
      summary: Get a list of logs
      description: Gets the list of logs.
      parameters:
        - name: path
          in: query
          description: The path to the directory to list logs under.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  logfiles:
                    type: array
                    items:
                      $ref: "#/components/schemas/LogFile"
                    example:
                      - "log1.log"
                      - "log2.log"
                required:
                  - logfiles
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Directory not found"
                required:
                  - message
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Path not found"
                required:
                  - message
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
                required:
                  - message
components:
  schemas:
    LogFile:
      type: object
      properties:
        dir:
          type: boolean
          example: false
        name:
          type: string
          example: "log1.log"
      required:
        - dir
        - name
